NewsWebPage/Areas/Admin/Controllers/AdminSiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWebPage.Data;
using NewsWebPage.Models.ViewModel;
using NewsWebPage.Utility;

namespace NewsWebPage.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class AdminSiteController : Controller
    {
        private readonly ApplicationDbContext _db;

        public IActionResult Index()
        {
            StatisticalViewModel board = new StatisticalViewModel();
            //board.Posts_Count = _db.Posts.Count();
            //board.Authors_Count = _db.Authors.Count();
            return View();
        }
    }
}

NewsWebPage/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsWebPage.Data;
using NewsWebPage.Models;
using NewsWebPage.Models.ViewModel;
using NewsWebPage.Utility;

namespace NewsWebPage.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        [BindProperty]
        public PostViewModel PostVM { get; set; }

        public PostController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            PostVM = new PostViewModel()
            {
                Post = new Models.Post(),

                Categories = _context.Categories,
                SpecialTags = _context.SpecialTags
            };
        }

        public async Task<IActionResult> Index()
        {
            var post = _context.Posts.Include(m => m.SpecialTags).Include(m => m.Category).Include(m => m.SpecialTags);
            return View(await post.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(PostVM);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return View(PostVM);
            }

            _context.Posts.Add(PostVM.Post);

            await _context.SaveChangesAsync();

            string webRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var postFromDb = _context.Posts.Find(PostVM.Post.Id);
            postFromDb.DateCreated = DateTime.Now;

            if (files.Count != 0)
            {
                var uploads = Path.Combine(webRootPath, SD.DefaultImageFolder);
                var extension = Path.GetExtension(files[0].FileName);

                using (var filestream = new FileStream(Path.Combine(uploads, PostVM.Post.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }
                postFromDb.Image = @"\" + SD.DefaultImageFolder + @"\" + PostVM.Post.Id + extension;
            }
            else
            {
                var uploads = Path.Combine(webRootPath, SD.DefaultImageFolder + @"\" + SD.DefaultImage);
                System.IO.File.Copy(uploads, webRootPath + @"\" + SD.DefaultImageFolder + @"\" + PostVM.Post.Id + ".png");
                postFromDb.Image = @"\" + SD.DefaultImageFolder + @"\" + PostVM.Post.Id + ".png";
            }
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostVM.Post = await _context.Posts.Include(m => m.SpecialTags).Include(m => m.Category).SingleOrDefaultAsync(m => m.Id == id);

            if (PostVM.Post == null)
            {
                return NotFound();
            }

            return View(PostVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var productFromDb = _context.Posts.Where(m => m.Id == PostVM.Post.Id).FirstOrDefault();

                if (files.Count > 0 && files[0] != null)
                {
                    var uploads = Path.Combine(webRootPath, SD.ProductImageFolder);
                    var extension_new = Path.GetExtension(files[0].FileName);
                    var extension_old = Path.GetExtension(productFromDb.Image);

                    if (System.IO.File.Exists(Path.Combine(uploads, PostVM.Post.Id + extension_old)))
                    {
                        System.IO.File.Delete(Path.Combine(uploads, PostVM.Post.Id + extension_old));
                    }
                    using (var filestream = new FileStream(Path.Combine(uploads, PostVM.Post.Id + extension_new), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    PostVM.Post.Image = @"\" + SD.ProductImageFolder + @"\" + PostVM.Post.Id + extension_new;
                }

                if (PostVM.Post.Image != null)
                {
                    productFromDb.Image = PostVM.Post.Image;
                }

                productFromDb.Name = PostVM.Post.Name;

                productFromDb.Author = PostVM.Post.Author;
                productFromDb.DateCreated = DateTime.Now;
                productFromDb.Content = PostVM.Post.Content;
                productFromDb.Description = PostVM.Post.Description;
                productFromDb.CategoryID = PostVM.Post.CategoryID;

                productFromDb.SpecialTagsID = PostVM.Post.SpecialTagsID;

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(PostVM);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostVM.Post = await _context.Posts.Include(m => m.Category).Include(m => m.SpecialTags).SingleOrDefaultAsync(m => m.Id == id);

            if (PostVM.Post == null)
            {
                return NotFound();
            }

            return View(PostVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PostVM.Post = await _context.Posts.Include(m => m.Category).Include(m => m.SpecialTags).SingleOrDefaultAsync(m => m.Id == id);

            if (PostVM.Post == null)
            {
                return NotFound();
            }

            return View(PostVM);
        }

        //POST : Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            Post post = await _context.Posts.FindAsync(id);

            if (post == null)
            {
                return NotFound();
            }
            else
            {
                var uploads = Path.Combine(webRootPath, SD.ProductImageFolder);
                var extension = Path.GetExtension(post.Image);

                if (System.IO.File.Exists(Path.Combine(uploads, post.Id + extension)))
                {
                    System.IO.File.Delete(Path.Combine(uploads, post.Id + extension));
                }
                _context.Posts.Remove(post);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }
    }
}

NewsWebPage/Areas/Admin/Controllers/RSSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.ServiceModel.Syndication;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWebPage.Common;
using NewsWebPage.Data;
using NewsWebPage.Models;
using NewsWebPage.Models.ViewModel;
using NewsWebPage.Utility;

namespace NewsWebPage.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RSSController : Controller
    {
        private readonly ApplicationDbContext _db;

        public RSSFeed RSSVM;

        public string data;

        public RSSController(ApplicationDbContext db)
        {
            _db = db;
            RSSVM = new RSSFeed();
        }

        public ActionResult PostFeed(string type)
        {
            Category category = _db.Categories.Where(s => s.Alias.Contains(type)).FirstOrDefault();
            if (category == null)
            {
                return BadRequest();
            }
            IEnumerable<Article> posts = (from s in _db.Articles where s.Category.Alias.Contains(type) select s).ToList();
            var feed = new SyndicationFeed(category.Name, "RSS Feed",
                new Uri("https://myblog.com/RSS"),
                Guid.NewGuid().ToString(),
                DateTime.Now
                );
            var items = new List<SyndicationItem>();
            foreach (Article art in posts)
            {
                string postUrl = String.Format("https://myblog.com/" + art.Alias + "-{0}", art.Id);
                var item =
                new SyndicationItem(Helper.RemoveIllegalCharacters(art.Title),
                Helper.RemoveIllegalCharacters(art.Description),
                new Uri(postUrl),
                art.Id.ToString(),
                art.DatePublished.Value
                );

                items.Add(item);
            }

            feed.Items = items;
            return new RSSActionResult { Feed = feed };
        }

        public ActionResult ReadRSS()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ReadRSS(string url)
        {
            WebClient wclient = new WebClient();
            wclient.Encoding = ASCIIEncoding.UTF8;
            if (url == null)
            {
                return BadRequest();
            };
            string RSSData = wclient.DownloadString(url);
            XDocument xml = XDocument.Parse(RSSData, LoadOptions.PreserveWhitespace);
            var RSSFeedData = (from x in xml.Descendants("item")
                               select new RSSFeed
                               {
                                   Title = ((string)x.Element("title")),
                                   Link = ((string)x.Element("link")),
                                   Description = ((string)x.Element("description")),
                                   PubDate = ((string)x.Element("pubDate"))
                               }
                               );

            ViewBag.RSSFeed = RSSFeedData;
            ViewBag.URL = url;

            return View();
        }

        [HttpPost, ActionName("SaveRSS")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveRSS(string url)
        {
            WebClient wclient = new WebClient();
            wclient.Encoding = ASCIIEncoding.UTF8;
            string RSSData = wclient.DownloadString(url);
            XDocument xml = XDocument.Parse(RSSData, LoadOptions.PreserveWhitespace);
            var RSSFeedData = (from x in xml.Descendants("item")
                               select new Article
                               {
                                   Title = ((string)x.Element("title")),
                                   Link = ((string)x.Element("link")),
                                   Description = ((string)x.Element("description")),
                                   DatePublished = ((DateTime)x.Element("pubDate"))
                               }
                               );

            if (!ModelState.IsValid)
            {
                return View(RSSVM);
            }

            _db.Articles.Add(RSSFeedData.FirstOrDefault());
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(ReadRSS));
        }
    }
}

NewsWebPage/Areas/Reader/Controllers/PostSaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewsWebPage.Data;
using NewsWebPage.Extensions;
using NewsWebPage.Models;
using NewsWebPage.Models.ViewModel;
using Microsoft.AspNetCore.Identity;

using System.Security.Claims;

namespace NewsWebPage.Areas.Reader.Controllers
{
    [Area("Reader")]
    public class PostSaveController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public PostSaveViewModel PostSaveVM { get; set; }

        public PostSaveController(ApplicationDbContext db)
        {
            _db = db;

            PostSaveVM = new PostSaveViewModel()
            {
                Posts = new List<Post>(),
                Reader = new ApplicationUser(),
                PostSave = new PostSave()
            };
        }

        public async Task<IActionResult> Index()
        {
            var ReaderID = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var postList = (IEnumerable<int>)(from ps in _db.PostSaves where ps.ReaderID == ReaderID select ps.PostID).ToList();

            foreach (var postitem in postList)
            {
                Post post = _db.Posts.Include(p => p.SpecialTags).Include(p => p.Category).Where(p => p.Id == postitem).FirstOrDefault();
                PostSaveVM.Posts.Add(post);
            }

            return View(PostSaveVM);
        }

        public IActionResult Remove(int id)
        {
            var ReaderID = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var postList = (IEnumerable<int>)(from ps in _db.PostSaves where ps.ReaderID == ReaderID select ps.PostID).ToList();
            if (postList.Count() > 0)
            {
                if (postList.Contains(id))
                {
                    PostSave post = _db.PostSaves.Where(p => p.PostID == id).Where(p => p.ReaderID == ReaderID).FirstOrDefault();
                    _db.PostSaves.Remove(post);
                    _db.SaveChanges();
                }
            }
            _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

NewsWebPage/Views/Shared/_AdminSite.cshtml
@using NewsWebPage.Utility;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Admin Dashboard</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" <a asp-action="Index" asp-controller="AdminSite">Dashboard</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <partial name="_LoginPartial" />
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        @if (User.IsInRole(SD.SuperAdminEndUser))
                        {
                            <div>
                                <div class="sb-sidenav-menu-heading">User</div>
                                <a class="nav-link" asp-area="Admin" asp-controller="ManageUser" asp-action="Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Quản lý tài khoản
                                </a>

                                <div class="sb-sidenav-menu-heading">Manage</div>

                                <a class="nav-link" asp-area="Admin" asp-controller="Categories" asp-action="Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Danh mục
                                </a>
                                <a class="nav-link" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Nhãn đặc biệt
                                </a>
                                <a class="nav-link" asp-area="Admin" asp-controller="Post" asp-action="Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Bài viết
                                </a>
                            </div>

                        }
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMaganementUser" aria-expanded="false" aria-controls="collapseMaganementUser">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Manage User
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseMaganementUser" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="Admin" asp-controller="ManageUser" asp-action="Index">Admin Users</a>
                            </nav>
                        </div>

                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    adminshop
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="content-wrapper">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Closthes Shop 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="~/assets/demo/datatables-demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NewsWebPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsWebPage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/menu.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/themify-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NewsWebPage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="RSS" asp-action="ReadRSS">RSS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Reader" asp-controller="PostSave" asp-action="Index">PostSave</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
        <script src="~/js/main.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

NewsWebPage/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model).Replace("%2F","/")">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model).Replace("%2F","/")">
            <i class="fas fa-list-alt"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model).Replace("%2F","/")">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>